APP_TITLE = "FIT2109 Log Tool"


def build_report(summary):
    result_lines = [APP_TITLE, "=" * len(APP_TITLE)]
    for key in sorted(summary):
        result_lines.append(f"{key}: {summary[key]}")
    result_lines.append("Generated by Log Tool")
    return "\n".join(result_lines)
